### ISSUE TITLE
--exclude_regions / -k flag not working in REDItools3 Docker 3.4 (AttributeError: 'RTChecks' object has no attribute 'check_exclusion')

### ISSUE THREAD

**Issue by AchiadChenzi** [BioinfoUNIBA/REDItools3#40]
Hi REDItools3 developers,

I'm running the latest official REDItools3 Docker image (chiaenu/reditools3:3.4 dated 2025-08-19 / quay.io/biocontainers/reditools3:3.4--pyhdfd78af_0). I would like to use the --exclude_regions (or -k) flag to ignore regions listed in a BED file during the analyze step, as per the documentation and CLI help.

However, as soon as I include the region exclusion argument, I get the error:

[ERROR] (<class 'AttributeError'>) 'RTChecks' object has no attribute 'check_exclusion'
This appears to be a bug in the main class implementation, as the attribute/method check_exclusion is not present in RTChecks in this version (latest on DockerHub/Quay).

How to reproduce:
Run any REDItools3 analysis with the --exclude_regions or -k flag and a standard BED file

Example:
bash
python -m reditools analyze sample.bam --reference genome.fa -k repeats.bed -o outfile.tsv
Expected behavior:
BED regions should be excluded from analysis as documented.

Actual result:
Program crashes with AttributeError (see above).

Environment:
Docker image: chiaenu/reditools3:3.4 or quay.io/biocontainers/reditools3:3.4--pyhdfd78af_0 (latest as of Oct 2025)

Host: Linux
Workarounds attempted:
Using both long (--exclude_regions) and short (-k) flag versions — same error.
Switching to previous Docker image versions — same error.

Feature/Bug Request:
Can you please fix this in the next release or provide a temporary workaround?
This feature is essential for modern RNA-editing pipelines to exclude repeats and problematic regions.

Thank you!
